### ISSUE TITLE
Can't convert from a set of lat,long to schematic map

### ISSUE THREAD

**Issue by korrio** [juliuste/transit-map#2]
my sample data:
https://gist.github.com/korrio/59fded98eeae399b472f6e132400a958

when run 
`cat iri.json | transit-map > iri.svg`

```
/Users/xxx/.nvm/versions/node/v8.9.0/lib/node_modules/transit-map/index.js:46
    gurobiPromise.childProcess.stderr.on('data', e => {throw new Error(e)})
                                                       ^
Error: gurobi_cl: can't open ResultFile=/var/folders/pg/995cyjn922bcnk7g00rtpc3m0000gn/T/transit-map-8922vEzj8Wfar2EH/solution.sol.nl

    at Socket.gurobiPromise.childProcess.stderr.on.e (/Users/korrio/.nvm/versions/node/v8.9.0/lib/node_modules/transit-map/index.js:46:62)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
```

**Comment by juliuste** [comment]
Sorry for the late response, **please re-open if you're still interested in an answer**, I'll try my best to help then.
